name: modinate_generator
description: The generator half of modinate.
version: 0.0.1
# homepage: https://www.example.com

publish_to: none

environment:
  sdk: ">=2.17.0-182.2.beta <3.0.0"

dependencies:
  build: ^2.3.0
  source_gen: ^1.2.2

dev_dependencies:
  build_runner: ^2.1.10
  lints: ^1.0.0
  test: ^1.16.0
