name: chapturn
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-182.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Dart.
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  dartz: ^0.10.1
  freezed_annotation: ^1.1.0

  # Router.
  auto_route: ^3.2.4

  # State management.
  hooks_riverpod: ^2.0.0-dev.5
  flutter_hooks: ^0.18.3

  # Database.
  drift: ^1.5.0
  sqlite3_flutter_libs: ^0.5.5
  path_provider: ^2.0.9
  path: ^1.8.1

  chapturn_sources:
    path: ../chapturn_sources
  connectivity_plus: ^2.3.0
  url_launcher: ^6.0.20
  logging: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.8
  mockito: ^5.1.0
  freezed: ^1.1.1
  drift_dev: ^1.5.2

flutter:
  uses-material-design: true

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
