name: nacht
description: Free and open source multi-platform novel reader.

publish_to: "none"

version: 0.1.3+4

environment:
  sdk: ">=2.17.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Dart.
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  dartz: ^0.10.1
  freezed_annotation: ^2.0.3
  logging: ^1.0.2
  crypto: ^3.0.2

  # Router.
  auto_route: ^4.0.1

  # State management.
  hooks_riverpod: ^2.0.0-dev.9
  flutter_hooks: ^0.18.3

  # Database.
  drift: ^1.5.0
  sqlite3_flutter_libs: ^0.5.5
  path_provider: ^2.0.9
  path: ^1.8.1

  # Network.
  connectivity_plus: ^2.3.0
  dio: ^4.0.6

  # Misc.
  url_launcher: ^6.0.20
  webview_flutter: ^3.0.2
  permission_handler: ^9.2.0

  nacht_sources:
    path: ../nacht_sources
  intl: ^0.17.0
  flutter_html: ^3.0.0-alpha.3
  shared_preferences: ^2.0.15
  collection: ^1.16.0
  google_fonts: ^3.0.1
  cached_network_image: ^3.2.1
  package_info_plus: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.8
  mockito: ^5.1.0
  freezed: ^2.0.3+1
  drift_dev: ^1.5.2

flutter:
  uses-material-design: true

  assets:
    - assets/google_fonts/
    - assets/google_fonts/Lato/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
