name: nacht
description: Free and open source multi-platform novel reader.

publish_to: "none"

version: 0.2.3+12

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Dart.
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  dartz: ^0.10.1
  freezed_annotation: ^2.0.3
  logging: ^1.0.2
  crypto: ^3.0.2
  collection: ^1.16.0

  # Router.
  auto_route: ^7.4.0

  # State management.
  riverpod: ^2.4.0
  hooks_riverpod: ^2.4.0
  flutter_hooks: ^0.20.1

  # Persistence
  drift: ^2.4.0
  sqlite3_flutter_libs: ^0.5.5
  path_provider: ^2.0.9
  path: ^1.8.1
  shared_preferences: ^2.0.15

  # Network.
  connectivity_plus: ^4.0.1
  dio: ^5.1.1
  cached_network_image: ^3.2.1

  # Widgets.
  scrollable_positioned_list: ^0.3.4
  flutter_widget_from_html_core: ^0.13.0-alpha.1
  fwfh_url_launcher: ^0.13.0-alpha.1
  fwfh_cached_network_image: ^0.13.0-alpha.1

  # Misc.
  url_launcher: ^6.0.20
  webview_flutter: ^4.0.1
  webview_flutter_android: ^3.1.1
  permission_handler: ^10.3.0

  # App specific
  nacht_sources:
    git:
      url: https://github.com/nacht-org/nacht_sources
      ref: v0.2.5

  # Rendering
  google_fonts: ^5.1.0
  dynamic_color: ^1.5.4
  boxy: ^2.0.7
  flutter_markdown: ^0.6.14
  fluttertoast: ^8.2.2
  simple_animations: ^5.0.0+3

  # Background
  workmanager: ^0.5.1
  flutter_local_notifications: ^15.0.1

  # Misc
  intl: ^0.18.0
  package_info_plus: ^4.0.2
  share_plus: ^7.0.2
  github: ^9.15.1
  system_info2: ^4.0.0
  version: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  auto_route_generator: ^7.1.1
  build_runner: ^2.1.8
  mockito: ^5.1.0
  freezed: ^2.0.3+1
  drift_dev: ^2.1.0
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.6.1

dependency_overrides: 
  http: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/google_fonts/
    - assets/google_fonts/Lato/
    - assets/google_fonts/Open_Sans/

flutter_icons:
  image_path: "assets/icon/favicon.png"
  android: true
