// Mocks generated by Mockito 5.1.0 from annotations
// in chapturn/test/data/mappers/database_mappers/companion_mappers/source_to_novel_companion_mapper_test.dart.
// Do not manually edit this file.

import 'package:chapturn/domain/mapper.dart' as _i2;
import 'package:chapturn_sources/chapturn_sources.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [Mapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockStatusMapper extends _i1.Mock
    implements _i2.Mapper<_i3.NovelStatus, int> {
  MockStatusMapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int map(_i3.NovelStatus? input) =>
      (super.noSuchMethod(Invocation.method(#map, [input]), returnValue: 0)
          as int);
}

/// A class which mocks [Mapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkTypeMapper extends _i1.Mock
    implements _i2.Mapper<_i3.WorkType, int> {
  MockWorkTypeMapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int map(_i3.WorkType? input) =>
      (super.noSuchMethod(Invocation.method(#map, [input]), returnValue: 0)
          as int);
}

/// A class which mocks [Mapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockReadingDirectionMapper extends _i1.Mock
    implements _i2.Mapper<_i3.ReadingDirection, int> {
  MockReadingDirectionMapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int map(_i3.ReadingDirection? input) =>
      (super.noSuchMethod(Invocation.method(#map, [input]), returnValue: 0)
          as int);
}
