// Mocks generated by Mockito 5.1.0 from annotations
// in chapturn/test/data/mappers/database_mappers/model_mappers/database_to_metadata_mapper.dart.
// Do not manually edit this file.

import 'package:chapturn/domain/mapper.dart' as _i2;
import 'package:chapturn_sources/src/models/metadata.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [Mapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockSeedToNamespaceMapper extends _i1.Mock
    implements _i2.Mapper<int, _i3.Namespace> {
  MockSeedToNamespaceMapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Namespace map(int? input) =>
      (super.noSuchMethod(Invocation.method(#map, [input]),
          returnValue: _i3.Namespace.dc) as _i3.Namespace);
}
