// Mocks generated by Mockito 5.1.0 from annotations
// in chapturn/test/data/mappers/database_mappers/model_mappers/database_to_novel_mapper_test.dart.
// Do not manually edit this file.

import 'package:chapturn/domain/mapper.dart' as _i3;
import 'package:chapturn_sources/chapturn_sources.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeWorkType_0 extends _i1.Fake implements _i2.WorkType {}

/// A class which mocks [Mapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockStatusMapper extends _i1.Mock
    implements _i3.Mapper<int, _i2.NovelStatus> {
  MockStatusMapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NovelStatus from(int? input) =>
      (super.noSuchMethod(Invocation.method(#map, [input]),
          returnValue: _i2.NovelStatus.ongoing) as _i2.NovelStatus);
}

/// A class which mocks [Mapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkTypeMapper extends _i1.Mock
    implements _i3.Mapper<int, _i2.WorkType> {
  MockWorkTypeMapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WorkType from(int? input) =>
      (super.noSuchMethod(Invocation.method(#map, [input]),
          returnValue: _FakeWorkType_0()) as _i2.WorkType);
}

/// A class which mocks [Mapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockReadingDirectionMapper extends _i1.Mock
    implements _i3.Mapper<int, _i2.ReadingDirection> {
  MockReadingDirectionMapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ReadingDirection from(int? input) =>
      (super.noSuchMethod(Invocation.method(#map, [input]),
          returnValue: _i2.ReadingDirection.ltr) as _i2.ReadingDirection);
}
