// Mocks generated by Mockito 5.1.0 from annotations
// in chapturn/test/domain/usecases/parse_or_get_novel_test.dart.
// Do not manually edit this file.

import 'package:chapturn/data/datasources/local/database.dart' as _i2;
import 'package:chapturn/domain/mapper.dart' as _i3;
import 'package:chapturn_sources/src/models/novel.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeNovelsCompanion_0 extends _i1.Fake implements _i2.NovelsCompanion {}

/// A class which mocks [Mapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockNovelCompanionFromNovelMapper extends _i1.Mock
    implements _i3.Mapper<_i4.Novel, _i2.NovelsCompanion> {
  MockNovelCompanionFromNovelMapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NovelsCompanion map(_i4.Novel? input) =>
      (super.noSuchMethod(Invocation.method(#map, [input]),
          returnValue: _FakeNovelsCompanion_0()) as _i2.NovelsCompanion);
}
